@startsalt LofiCreateFlatGroup


{^"Create Flat Group" 
    {Please fill out the below to set up a Flat Group}
    **Group Name**|  "Example Group           " 
    

    Group Tasks | {SI
    **List of Tasks**
    Clean the kitchen
    Vacuum the living room
    Trash
    Water the plants
    .
    
    
    }
    . | [Add Task]

    ----|----
    Selected Group Tasks | {SI
    **Tasks**
    Clean the kitchen
    Vacuum the living room
    }

    ---- | ----
    Add Flat Members  | {SI 
    **Email Addreess** 
    John@ihug.com
    chuckycheese@gmail.com
    }
    . | [Add Members]


    ====|====
    **Add Group** | [Cancel]|[ OK ]

}

@endsalt