@startsalt LoFiCustomerRegistration


{^"Create Task" 
    {Please enter the following information related to the task}
    **Task ID** | "1234567890" (autuo-generated)
    **Task Name**|  "Dishes            " 
    **Submit ** | [Cancel]|[ OK ]

}

@endsalt